-- ============================================================================
--  Patch for the Supabase linter advisories raised against schema.sql
--  Run AFTER schema.sql. Safe to run more than once.
--  These fixes are folded into schema.sql too, so a fresh project needs only
--  schema.sql — this file exists for projects already created.
-- ============================================================================

-- 1. CRITICAL — "Security Definer View" on public.question_counts
--    A Postgres view runs with the privileges of its OWNER by default, so it
--    reads through row-level security rather than under it. Here that leaks
--    little (vote rows are world-readable anyway), but a view that silently
--    bypasses RLS is a bad thing to leave lying around for someone to reuse.
--    security_invoker makes it run as the CALLER instead.
alter view public.question_counts set (security_invoker = on);

-- 2. "Function Search Path Mutable" on is_moderator and check_question_rate
--    Without a pinned search_path, someone able to create objects in an earlier
--    schema could shadow a table or function these rely on. Pin it.
create or replace function public.is_moderator() returns boolean
  language sql stable
  set search_path = public, pg_temp
as $$
  select coalesce(auth.jwt() ->> 'email', '') like '%@empiricbusinessmedia.com'
$$;

create or replace function public.check_question_rate() returns trigger
  language plpgsql
  set search_path = public, pg_temp
as $$
declare recent int;
begin
  select count(*) into recent
  from questions
  where board_code = new.board_code
    and created_at > now() - interval '10 minutes'
    and author_name = new.author_name
    and author_company = new.author_company;
  if recent >= 5 then
    raise exception 'Too many questions in a short time. Please wait a moment.';
  end if;
  return new;
end $$;

-- 3. "Multiple Permissive Policies" on public.boards
--    boards_read covers SELECT and boards_write was FOR ALL, which also covers
--    SELECT — so every read evaluated two policies. Split the write policy into
--    the three verbs it actually needs.
drop policy if exists boards_write on boards;
create policy boards_insert on boards for insert with check (is_moderator());
create policy boards_update on boards for update using (is_moderator()) with check (is_moderator());
create policy boards_delete on boards for delete using (is_moderator());

-- 4. "RLS Policy Always True" on public.votes — READ THIS ONE
--    votes_delete was `using (true)`, meaning ANY client could delete ANY vote
--    row, not just their own. Someone could strip the votes off a question they
--    disliked and quietly sink it down the board. That is a real flaw, not a
--    lint nit.
--
--    It CANNOT be fixed by a policy while voting is anonymous, and it is worth
--    being plain about why rather than shipping something that looks like a fix:
--
--      * voter_id is generated by the browser and sent in the request. RLS has
--        no authenticated identity to compare it against, so a policy cannot
--        tell "my vote" from "someone else's".
--      * moving the toggle into a SECURITY DEFINER function does not close it
--        either, because votes are world-readable (the client needs them to
--        count), so any voter_id can simply be read and then passed in.
--
--    The only real fix is authenticating voters — at which point voter_id
--    becomes auth.uid() and the policy writes itself:
--        create policy votes_delete on votes for delete
--          using (voter_id = auth.uid()::text);
--
--    Left permissive here DELIBERATELY, because this is a test project with
--    invented questions and the alternative would be disabling un-voting. It is
--    a PRODUCTION BLOCKER, recorded in README.md — do not run a real event on a
--    project with this policy in place.
--    (votes_delete from schema.sql is intentionally left as-is.)

select 'Advisory patch applied. Re-run the linter to confirm.' as status;
